language: node_js

os:
  - osx
  - windows

node_js:
  - node

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -Command 'Get-ItemProperty -Path HKLM:\\System\\CurrentControlSet\\Control\\Lsa -Name DisableDomainCreds -Value 0'; fi